### ISSUE TITLE
Breaking changes after new release

### ISSUE THREAD

**Issue by devantler** [otherguy/docker-yamlfix#37]
Traceback (most recent call last):
  File "/usr/local/bin/yamlfix", line 5, in <module>
    from yamlfix.entrypoints.cli import cli
  File "/usr/local/lib/python3.11/site-packages/yamlfix/__init__.py", line 10, in <module>
    from yamlfix.services import fix_code, fix_files
  File "/usr/local/lib/python3.11/site-packages/yamlfix/services.py", line 13, in <module>
    from yamlfix.adapters import SourceCodeFixer, Yaml
  File "/usr/local/lib/python3.11/site-packages/yamlfix/adapters.py", line 14, in <module>
    from yamlfix.model import YamlfixConfig, YamlNodeStyle
  File "/usr/local/lib/python3.11/site-packages/yamlfix/model.py", line 5, in <module>
    from maison.schema import ConfigSchema
ModuleNotFoundError: No module named 'maison.schema'

**Comment by devantler** [comment]
I am not sure if Maison is the only one that will cause issues.

Otherwise we might need to add the ones referenced here:

https://lyz-code.github.io/yamlfix/#references

I suggest we try one by one, as I am confused the dependencies are not automatically installed by `pip install yamlfix`. I would expect that, but for maison it seems not to be the case.

**Comment by otherguy** [comment]
@devantler first of all thanks for contributing! 😄 I had neglected this repository a bit. 

To the dependency issues, I was as surprised as you are. `pip install yamlfix` should install all its dependencies.

**Comment by otherguy** [comment]
@devantler thank you again for your PRs and pushing me to update this! I mentioned you in the [`Acknowledgements` section of the README](https://github.com/otherguy/docker-yamlfix?tab=readme-ov-file#%EF%B8%8F-acknowledgements).

I have also made the container non-privileged by default and released version 1.1.0:

```bash
$ docker run --rm -it otherguy/yamlfix:1.1.0
```

Or:

```bash
$ whalebrew install otherguy/yamlfix
$ yamlfix
```
